name: CI/CD Pipeline

on:
  push:
    branches: [dev, test, main]
  pull_request:
    branches: [dev, test, main]

jobs:
  dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build (Dev)
        run: yarn build

      - name: Run Tests
        run: yarn test

  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build (Test)
        run: yarn build

      - name: Run Tests
        run: yarn test

  production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build (Prod)
        run: yarn build

      - name: Configure Git
        run: |
          git config --global user.name "gjrkdk"
          git config --global user.email "89792219+GJRKZB@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        run: |
          BUILD_DIR="dist"

          # Clone the gh-pages branch in a separate directory
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages

          # Remove old content and copy new build files
          rm -rf gh-pages/*
          cp -r $BUILD_DIR/* gh-pages/

          # Commit and push changes
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages from ${GITHUB_SHA}"
          git push origin gh-pages
