name: CI/CD Pipeline

on:
  push:
    branches: [dev, test, main]
  pull_request:
    branches: [dev, test, main]

permissions:
  contents: write # For checking out code, etc.
  pages: write # Required by actions/deploy-pages@v1
  id-token: write # Required by actions/deploy-pages@v1

jobs:
  ####################################################################
  # DEV stage - runs when pushing/PR to "dev" branch
  ####################################################################
  dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build (Dev)
        run: yarn build # Or a separate dev build if you prefer

      - name: Run Tests
        run: yarn test

  ####################################################################
  # TEST stage - runs when pushing/PR to "test" branch
  ####################################################################
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build (Test)
        run: yarn build

      - name: Run Tests
        run: yarn test

  ####################################################################
  # PRODUCTION BUILD job - runs when pushing/PR to "main" branch
  ####################################################################
  build-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build (Production)
        run: yarn build # This should produce ./dist with index.html, bundle.js, etc.

      # Upload the dist folder as an artifact to be used by the deploy job
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"

  ####################################################################
  # PRODUCTION DEPLOY job - uses official "deploy-pages" action
  ####################################################################
  deploy-production:
    runs-on: ubuntu-latest
    needs: build-production # Waits for the build-production job to finish
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
        with:
          # No need to specify publish_dir here, because it uses the artifact from "upload-pages-artifact"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Deployment URL
        run: echo "Your production site is live at https://gjrkdk.github.io/auto-cicd-workflow/"
